### PR TITLE
Pressure Converter now has steam pushing mode

### LINKED ISSUE #136: Way to use pressure converter without buildcraft pipe
Hi and many thanks for excellent mod!

I have server with IndustrialCraft2 and RailCraft + ProjectRed.

I use ProjectRed instead buildcraft on my server and i have no any fluid pipes.

RC (RailCraft) steam converted to FSP steam via Pressure Converter, but i not found way to convert FSP steam back to fluid steam (

As far i understand it happen because block connected to converter must pull fluid steam from converter (Like wood pipe in buildcraft). Rc and IC2 not have any device for this (

Will be good if FSP would be have it.

Thanks!

### PR DESCRIPTION
**Pull request by Ghoughpteighbteau**
Comes with matching graphic and entry!

Disconnected Ring
Second Page

Please please please vet these code changes, because I am not a veteran minecraft modder. 

fixes #136

also... I think my grammar might be shit.... and I made a f&$%#ng typo. :sob:

### CODE REVIEW

**Comment by Ghoughpteighbteau** [comment]
how about: 
research.FSC.1=As an alternative to manually extracting liquid steam, I can disengage the pump ring of the Pressure Converter by using a wrench while sneaking. This will use the system's high pressure to force fluid steam into nearby tanks. However, doing so will prevent the Pressure Converter from converting liquid steam back into high pressure.
research.FSC.2=The rate at which the Pressure Converter ejects fluid steam depends on the pressure in the system. Operating at high pressure, I have witnessed no less than 4 buckets of steam per second.

**Comment by Ghoughpteighbteau** [comment]
:| ?

**Comment by xbony2** [comment]
I'm willing to merge it if you are :P your research text seems fine to me.

**Comment by Ghoughpteighbteau** [comment]
@xbony2 I found a bug regarding buildcraft pipes and the converter that crops up when IC2 isn't installed. It's preventing me from doing proper tests with these changes. Do you want the fix as a separate pull request or just submit it as part of this one?

**Comment by xbony2** [comment]
Feel free to submit it as part of this one, be easier that way. That bug is #172, I believe.

**Comment by Ghoughpteighbteau** [comment]
OK. Pretty sure dis works @xbony2 

Learned a bit about buildcraft today.

**Comment by xbony2** [comment]
Alright, here goes nothing :P

**Pull request merged**
